# Generated by Django 5.2 on 2025-05-05 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_data_for_training', models.BooleanField(default=False)),
                ('face_front', models.TextField()),
                ('face_left', models.TextField()),
                ('face_right', models.TextField()),
                ('yolo_face_front', models.TextField()),
                ('yolo_face_left', models.TextField()),
                ('yolo_face_right', models.TextField()),
                ('general_disease_masks_front', models.JSONField()),
                ('general_disease_masks_left', models.JSONField()),
                ('general_disease_masks_right', models.JSONField()),
                ('acne_mask_front', models.TextField()),
                ('acne_mask_left', models.TextField()),
                ('acne_mask_right', models.TextField()),
                ('face_frontal_results', models.JSONField()),
                ('face_left_results', models.JSONField()),
                ('face_right_results', models.JSONField()),
                ('public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
